CREATE SCHEMA IF NOT EXISTS DONASANGRE;
DROP TABLE IF EXISTS DONASANGRE.donante;
DROP SEQUENCE IF EXISTS DONASANGRE.hibernate_sequence;
CREATE SEQUENCE DONASANGRE.hibernate_sequence;
 
CREATE TABLE DONASANGRE.donante (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NOMBRE VARCHAR(250) NOT NULL,
  CARNE_DONANTE VARCHAR(250) NOT NULL,
  GRUPO VARCHAR (2) NOT NULL,
  RH VARCHAR(1) NOT NULL
);